MODULE CategoryLot;

REQUIRE Category, Lot;

NAMESPACE MasterData;

//category
dataUseLot 'Партионный учет' = DATA BOOLEAN (Category);
useLot (Category c) = useLot() AND (GROUP LAST dataUseLot(Category cp) ORDER level(c, cp)) MATERIALIZED;

EXTEND FORM category
    PROPERTIES (c) dataUseLot SHOWIF useLot();
    
DESIGN category {
    tabs {
        NEW lot {
            caption = 'Партии'; 
            MOVE PROPERTY(dataUseLot(c));
        }
    }
} 