MODULE ReceiptLotPrint;

REQUIRE ReceiptPrint, ReceiptLot, LotPrint;

NAMESPACE Inventory;

EXTEND FORM printReceipt
    OBJECTS lot = Lot SUBREPORT 'LotBarCode.jrxml'
    PROPERTIES(lot) READONLY id
    FILTERS done(l, lot)
;

printLot '{Label}' (ReceiptLine l) {
    count(Item i) <- 1 IF product(l) = i;
    count(Lot lot) <- done(l, lot);
    printLot();
}

EXTEND FORM receipt
    PROPERTIES(l) printLot SHOWIF countPrintType(product(l)) AND doneLot(l) DRAW lotL
;