MODULE BarCodeMobile;

REQUIRE BarCode;

NAMESPACE MasterData;

barCodeFilter '' = DATA LOCAL STRING[50] () CHARWIDTH 13;

META defineBarCodeFilter(form, obj, container)
    EXTEND FORM form
        PROPERTIES() barCodeFilter
        FILTERS (GROUP SUM 1 IF endsWith(id(BarCode b), barCodeFilter()) AND item(b) = obj) OR NOT barCodeFilter()
    ;
    DESIGN form {
        container {
            MOVE PROPERTY(barCodeFilter()) { placeholder = 'Barcode'; alignment = STRETCH; }
        }
    }
END
