MODULE SalesPricelistItem;

REQUIRE SalesPricelist, Item;

NAMESPACE Sales;

EXTEND FORM item   
    OBJECTS prls = PricelistLine 
    PROPERTIES(prls) READONLY startDate, endDate, note
    FILTERS item(prls) = i
    
    OBJECTS tc = PriceType GRID
    FILTERS editIn(prls, tc) 
    
    PROPERTIES(prls, tc) price COLUMNS (tc) HEADER name(tc)
;

DESIGN item {
    tabs {
        sale {
            MOVE BOX(prls) { showIf=canBeSold(i); };
            REMOVE BOX(tc);
        }
    }
}
