MODULE LocationEmployeeRu;

REQUIRE Location, Individual;

NAMESPACE Inventory;

DESIGN location {
    tabbedPane {
        NEW invoicePrint {
            caption = 'Invoice printing';
        }
    }
}

@defineEmployee(allowed, 'Отпуск разрешил', location, l, invoicePrint);
@defineEmployee(accountant, 'Главный (старший) бухгалтер', location, l, invoicePrint);
@defineEmployee(performed, 'Отпуск произвел', location, l, invoicePrint);
