MODULE TaskNotify;

REQUIRE Task;

NAMESPACE ProjectManagement;

notifyAssignedTo (Task t) {
    FOR assignedTo(t, Employee e) AND pushConnection(e) DO {
        NEWTHREAD {
            SHOW task OBJECTS t = t DOCKED NOWAIT;
        } TO exportInteger;
        pushNotify(pushConnection(e), (CONCAT ' : ', 'New task assigned', idName(t)), exportInteger());
    }
}

WHEN SETCHANGED(assignedTo(Task t)) DO
    notifyAssignedTo(t);