MODULE ReceiptSearch;

REQUIRE ReceiptDone, Doc;

NAMESPACE Inventory;

@defineDocSearch(receipt, product, initialDemand,r);

DESIGN receipt {
    pane2 {
        type = TABBED;
        NEW pane33 {
            caption = 'Подбор';
            type = SPLITH;
            fill = 1;
            MOVE BOX(TREE categories);
            MOVE BOX(itm) { 
                fill = 2; 
            }
        }     
    }
}


