MODULE ReceiptInitial;

REQUIRE ReceiptType;

NAMESPACE Inventory;

loadInitialData () + {
    NEW r = ReceiptType {
        name(r) <- 'Поступление';
        id(r) <- 'receipt';
        NEW n = Numerator {
            name(n) <- 'Поступление';
            series(n) <- 'ПП';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(r) <- n;
        }
    }
}