MODULE ReceiptPartner;

REQUIRE ReceiptDone;

NAMESPACE Inventory;

EXTEND FORM partner
    OBJECTS r = Receipt
    PROPERTIES(r) READONLY nameStatus, number, scheduledDateTime, executionDateTime, nameType, nameLocation, note
    PROPERTIES(r) NEWSESSION EDIT
    FILTERS vendor(r) = p
;

DESIGN partner {
    tabs {
        NEW receipts {
            caption = 'Приемки';
            MOVE BOX(r);
        }
    }
}
