MODULE ReceiptPartner;

REQUIRE ReceiptDone;

NAMESPACE Inventory;

EXTEND FORM partner
    OBJECTS r = Receipt
    PROPERTIES(r) READONLY number, scheduledDateTime, imagedNameStatus, nameType, executionDateTime, nameLocation, vendorReference, note
    PROPERTIES(r) NEWSESSION EDIT
    FILTERS vendor(r) = p
;

DESIGN partner {
    tabs {
        NEW receipts {
            caption = 'Receipts';
            MOVE BOX(r) { caption = ''; }
        }
    }
}
