MODULE PartnerSale;

REQUIRE MasterData, Partner;

NAMESPACE MasterData;

isCustomer 'Покупатель' = DATA BOOLEAN (Partner);

WHEN LOCAL SET(Partner p IS Partner) DO {
     isCustomer(p) <- TRUE;
}

EXTEND FORM partner 
    PROPERTIES(p) isCustomer
;

DESIGN partner {
    tabs {
        NEW customer {
            caption = 'Покупатель';
            NEW customerOptions {
                MOVE PROPERTY(isCustomer(p));
            }
        }
    }
}