MODULE InventorySettings;

NAMESPACE Inventory;

FORM options 'Настройки'
;

DESIGN options {
    OBJECTS {
        NEW general {
        
        }
    }
}

NAVIGATOR {
    NEW FOLDER stock 'Склад' WINDOW toolbar { 
        NEW FOLDER operations 'Операции' {
        }
        NEW FOLDER reporting 'Отчеты' {
        }
        NEW FOLDER settings 'Настройка' {
            NEW options;
        }
    }
}

