MODULE AccountReport;

REQUIRE Payment;

NAMESPACE Invoicing;

FORM accountReport 'Остатки по счетам'
    OBJECTS a = Account
    PROPERTIES(a) READONLY nameType, number, nameAccountHolder, notes, inAmount, outAmount, balance
    
    OBJECTS p = Payment
    PROPERTIES(p) READONLY date, fromAccountName, toAccountName, amount
    FILTERS toAccount(p) = a OR fromAccount(p) = a
;

NAVIGATOR {
    invoicing {
        reporting{
            NEW accountReport;        
        }
    }
}
