MODULE AccountReport;

REQUIRE Payment;

NAMESPACE Invoicing;

FORM accountReport 'Остатки по счетам'
    OBJECTS a = Account
    PROPERTIES(a) READONLY  accountNumber, nameAccountHolder, notes, inAmount, outAmount, balance
    
    OBJECTS p = Payment
    PROPERTIES(p) date, fromAccountNumber, toAccountNumber, amount
    FILTERS toAccount(p) = a OR fromAccount(p) = a
;

NAVIGATOR {
    invoicing {
        reports{
            NEW accountReport;        
        }
    }
}
