MODULE Retail;

REQUIRE RetailSettings,
        Pos, Session,
        PaymentMethod, PaymentMethodInitial,
        PosDashboard, PosDashboardSearch, 
        PosDashboardPayment, PosDashboardCash, PosDashboardCashInitial, 
        PosDashboardReturn, PosDashboardReturnPayment, 
        PosDashboardOrder, PosDashboardShipment,
        DiscountCard, PosDashboardDiscountCard,
        DiscountCardPartner, CashRegister;