MODULE RetailSettings;

NAMESPACE Retail;

FORM options 'Настройки';

DESIGN options {
    OBJECTS {
        NEW tabbedPane {
            type = TABBED;
            fill = 1;
        }
    }
} 

NAVIGATOR {
    NEW FOLDER retail 'Розничная торговля' WINDOW toolbar {
        NEW FOLDER operations 'Операции' {  
        }
        NEW FOLDER settings 'Настройка' {
            NEW options;        
        }
    }
}