MODULE Retail;

REQUIRE RetailSettings,
        Pos, Session,
        PaymentMethod, PaymentMethodInitial,
        PosDashboard, PosDashboardSearch, PosDashboardTouch, PosDashboardHotKey,
        PosDashboardPayment, PosDashboardCash, PosDashboardCashInitial, 
        PosDashboardReturn, PosDashboardReturnPayment, PosDashboardReturnLot,
        PosDashboardOrder, PosDashboardShipment, PosDashboardLot,
        DiscountCard, PosDashboardDiscountCard,
        DiscountCardPartner;