MODULE BillInitial;

REQUIRE BillType;

NAMESPACE Invoicing;

loadDefaultData () + {
    NEW t = BillType {
        name(t) <- 'Закупка у поставщика';
        id(t) <- 'wholesale';
        NEW n = Numerator {
            name(n) <- 'Закупка у поставщика';
            series(n) <- 'ПРП';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(t) <- n;
        }
    }
}