MODULE BillPayment;

REQUIRE Invoice, Bill, Payment;

NAMESPACE Invoicing;

bill 'Счет' = DATA Bill (Payment);


EXTEND FORM bills
    OBJECTS (b = Bill, p = Payment)
    PROPERTIES(b) READONLY date, dueDate, namePartner, notes, untaxedAmount, totalTax, totalAmount
    PROPERTIES (p) READONLY amountPaid
    PROPERTIES(b) NEWSESSION NEW, EDIT, DELETE
    FILTERS bill(p) = b
    
    LIST Bill OBJECT b;
;