MODULE BillUom;

REQUIRE Bill, PartnerUom, ItemUom;

NAMESPACE Invoicing;

@defineDocumentPartnerUom(Bill);
@defineDocumentPartnerQuantity(Bill);
@defineDocumentPartnerPrice(Bill);

EXTEND FORM bill
    PROPERTIES(l) SHOWIF otherUom(vendor(b)) BEFORE quantity(l) BACKGROUND RGB(255,212,255)
                  namePartnerUom, 
                  partnerQuantity ON CHANGE changePartnerQuantity(l),
                  partnerPrice ON CHANGE changePartnerPrice(l)
;