MODULE BillUom;

REQUIRE Bill, PartnerUom, ItemUom;

NAMESPACE Invoicing;

@defineDocPartnerUom(Bill);
@defineDocPartnerQuantity(Bill);
@defineDocPartnerPrice(Bill);

EXTEND FORM bill
    PROPERTIES(l) READONLYIF readonly(b) SHOWIF otherUom(vendor(b)) BEFORE quantity(l) BACKGROUND RGB(255,212,255)
                  namePartnerUom, 
                  partnerQuantity ON CHANGE changePartnerQuantity(l),
                  partnerPrice ON CHANGE changePartnerPrice(l)
;