MODULE BillUom;

REQUIRE Bill, PartnerUom, ItemUom;

NAMESPACE Invoicing;

@defineDocumentVendorUom(Bill);
@defineDocumentVendorQuantity(Bill);
@defineDocumentVendorPrice(Bill);

EXTEND FORM bill
    PROPERTIES(l) SHOWIF otherUom(vendor(b)) BEFORE quantity(l) BACKGROUND RGB(255,212,255)
                  nameVendorUom, 
                  vendorQuantity ON CHANGE changeVendorQuantity(l),
                  vendorPrice ON CHANGE changeVendorPrice(l)
;