MODULE BillInitial;

REQUIRE BillType;

NAMESPACE Invoicing;

loadDefaultData () + {
    NEW t = BillType {
        name(t) <- 'Поступление';
        id(t) <- 'bill';
        NEW n = Numerator {
            name(n) <- 'Поступление';
            series(n) <- 'ПРП';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(t) <- n;
        }
    }
}