MODULE AdjustmentJournalEntryInitial;

REQUIRE AdjustmentJournalEntry, GLAccountInitial, Adjustment, Journal;

NAMESPACE Inventory;

loadDefaultData () + {
    journal(AdjustmentType t) <- journal('miscellaneous') WHERE t IS AdjustmentType;
    costAmountDebitAccount(AdjustmentType t) <- GLAccount('5900') WHERE t IS AdjustmentType;
    costAmountCreditAccount(AdjustmentType t) <- GLAccount('1200') WHERE t IS AdjustmentType;
}
