MODULE Color;

REQUIRE Utils;

NAMESPACE Utils;

CLASS Color 'Colour' {
    primary 'Primary',
    secondary 'Secondary',
    success 'Success',
    info 'Info',
    warning 'Warning',
    danger 'Danger',
    light 'Light',
    dark 'Dark'
}

id '{ID}' (Color t) = getWord(staticName(t), '.', 2) IF t IS Color CHARWIDTH 10;
name '{Name}' (Color t) = staticCaption(t) IF t IS Color CHARWIDTH 10;

FORM colors 'Colours'
    OBJECTS c = Color
    PROPERTIES(c) READONLY name
    LIST Color OBJECT c
;
