MODULE Documentation;

REQUIRE MarkdownViewer;

NAMESPACE Utils;

showDocumentation 'Documentation' () {
    readResource('docs/' + language(currentUser()) + '/overview.md');
    showMarkdownResourceViewer('Documentation', 'docs/' + (IF resource() THEN language(currentUser()) ELSE 'en') + '/overview.md');
}

NAVIGATOR {
    NEW showDocumentation WINDOW system PARENT FIRST HEADER 'Documentation' IMAGE r'question';
}
