MODULE Documentation;

REQUIRE MarkdownViewer;

NAMESPACE Utils;

showDocumentation 'Documentation' () {
    FOR STRING f = 'docs/' + language(currentUser()) + '/overview.md' DO {
        readResource(f);
        showMarkdownResourceViewer('Documentation', IF resource() THEN f ELSE 'docs/en/overview.md');
    }
}

NAVIGATOR {
    NEW showDocumentation WINDOW system PARENT FIRST HEADER 'Documentation' IMAGE r'question';
}
