MODULE GeoUtils;

REQUIRE SystemEvents;

NAMESPACE GeoUtils;

// to delete

timestamp = DATA LOCAL LONG ();
latitude = DATA LOCAL NUMERIC[11,6] ();
longitude = DATA LOCAL NUMERIC[11,6] ();

changeCurrentPosition_mc () {
    INPUT pos = JSON DO {
        LOCAL coords = JSON ();
        IMPORT JSON FROM pos TO() timestamp, coords;
        IMPORT JSON FROM coords() TO() latitude, longitude;
    }
}

onWebClientInit() + {
    onWebClientInit('geoutils.js') <- 1;
}
