MODULE SalesOrderPrintInitial;

REQUIRE SalesOrderPrint, SalesOrderInitial;

NAMESPACE Sales;

loadDefaultData () + {
    NEW tm = OrderTemplate {
        name(tm) <- r'Quotation';
        template(tm) <- r'SalesQuotation.jrxml';
        in(tm, OrderType t) <- TRUE;
    }
    NEW tm = OrderTemplate {
        name(tm) <- r'Sales order';
        template(tm) <- r'SalesOrder.jrxml';
        in(tm, OrderType t) <- TRUE;
    }
}
