MODULE PurchaseOrderPrintInitialRu;

REQUIRE PurchaseOrderPrint, DocTemplate;

NAMESPACE Purchase;

loadDefaultData () + {
    NEW tm = OrderTemplate {
        name(tm) <- 'Заказ поставщику';
        template(tm) <- 'PurchaseOrderRu.jrxml';
        in(tm, OrderType t) <- TRUE;
    }
    NEW tm = OrderTemplate {
        name(tm) <- 'Запрос ценового предложения';
        template(tm) <- 'PurchaseQuoteRu.jrxml';
        in(tm, OrderType t) <- TRUE;
    }
}