MODULE MangoEmployeeCall;

REQUIRE MangoEmployee, Call;

NAMESPACE Mango;

callAvailable () += TRUE IF currentPBXUser();
call (STRING phone) +{
    urlEncode(phone, 'UTF-8');
    apiPost('commands/callback', JSON FROM command_id = r'outgoing',
                                          from = (JSON FROM extension = extensionCurrentPBXUser()),
                                          to_number = phone);
}
