MODULE ScrapPrint;

REQUIRE ScrapDone, DocTemplate;

NAMESPACE Inventory;

addressLocation 'Адрес' (Scrap s)  = linesAddress(location(s));

FORM printScrap 'Списание товара'
    OBJECTS s = Scrap PANEL 
    PROPERTIES(s) nameType, dateTime, nameLocation, addressLocation
    
    OBJECTS l = ScrapLine
    PROPERTIES(l) product, quantity
    FILTERS scrap(l) = s
;

@defineDocTemplate(scrap, 'списания');
@defineDocTemplateForm(scrap, s);