MODULE ScrapPrint;

REQUIRE ScrapDone, DocTemplate;

NAMESPACE Inventory;

addressLinesLocation 'Адрес' (Scrap s)  = addressLines(location(s));

FORM printScrap 'Списание'
    OBJECTS o = Scrap PANEL 
    PROPERTIES(o) nameType, dateTime, nameLocation, addressLinesLocation
    
    OBJECTS l = ScrapLine
    PROPERTIES(l) product, quantity
    FILTERS scrap(l) = o
;

@defineDocTemplateType(scrap, 'списания');
@defineDocTemplateTypeForm(scrap, s);