MODULE ProjectManagement;

REQUIRE Project, ProjectTimeEntry,
        ProjectPurchaseOrder,
        ProjectBill, ProjectPurchaseOrderBill,
        ProjectReceipt, ProjectPurchaseOrderReceipt,
        ProjectSalesOrder,
        ProjectInvoice, ProjectTimeEntryInvoice, ProjectSalesOrderInvoice,
        ProjectSalesLedgerInvoice, ProjectSalesLedgerReport,
        ProjectShipment, ProjectInvoiceShipment, ProjectSalesOrderShipment,
        ProjectManufacturingOrder;
