MODULE PurchaseOrderUom;

REQUIRE PurchaseOrder, PartnerUom, ItemUom;

NAMESPACE Purchase;

@defineDocumentVendorUom(Order);
@defineDocumentVendorQuantity(Order);
@defineDocumentVendorPrice(Order);

EXTEND FORM order
    PROPERTIES(l) SHOWIF otherUom(vendor(o)) BEFORE quantity(l) BACKGROUND RGB(255,212,255)
                  nameVendorUom, 
                  vendorQuantity ON CHANGE changeVendorQuantity(l),
                  vendorPrice ON CHANGE changeVendorPrice(l)
;