MODULE PurchaseOrderItem;

REQUIRE PurchaseOrder;

NAMESPACE Purchase;

EXTEND FORM item
    OBJECTS pl = OrderLine
    PROPERTIES(pl) READONLY nameStatus, number, dateTime, nameVendor, nameLocation, quantity, price
    PROPERTIES(pl) NEWSESSION EDIT
    FILTERS item(pl) = i
;

DESIGN item {
    operations {
        NEW pOrders {
            caption = 'Заказы поставщикам';
            MOVE BOX(pl);
        }
    }
}