MODULE PurchaseOrderItem;

REQUIRE PurchaseOrder;

NAMESPACE Purchase;

EXTEND FORM item
    OBJECTS pl = OrderLine
    PROPERTIES(pl) READONLY nameStatus, date, number, nameVendor, nameLocation, quantity, unitPrice
    PROPERTIES(pl) EDIT
    FILTERS item(pl) = i
;

DESIGN item {
    operations {
        NEW pOrders {
            caption = 'Заказы на закупку';
            MOVE BOX(pl);
        }
    }
}