MODULE PurchaseOrderInitial;

REQUIRE PurchaseOrderType;

NAMESPACE Purchase;

loadDefaultData () + {
    NEW t = OrderType {
        name(t) <- '{Order}';
        id(t) <- 'order';

        NEW n = Numerator {
            name(n) <- '{Order}';
            series(n) <- 'ZKP';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(t) <- n;
        }
    }
}