MODULE PurchaseOrderUom;

REQUIRE PurchaseOrder, PartnerUom, ItemUom;

NAMESPACE Purchase;

@defineDocumentPartnerUom(Order);
@defineDocumentPartnerQuantity(Order);
@defineDocumentPartnerPrice(Order);

EXTEND FORM order
    PROPERTIES(l) SHOWIF otherUom(vendor(o)) BEFORE quantity(l) BACKGROUND RGB(255,212,255)
                  namePartnerUom, 
                  partnerQuantity ON CHANGE changePartnerQuantity(l),
                  partnerPrice ON CHANGE changePartnerPrice(l)
;