MODULE OutgoingPaymentPrint;

REQUIRE OutgoingPayment, DocTemplate;

NAMESPACE Invoicing;

FORM printOutgoingPayment 'Исходящий платeж'

    OBJECTS p = OutgoingPayment PANEL 
    PROPERTIES(p)
        dateTime, number,
        namePartner, namePartnerAccount,
        nameCompany, nameCompanyAccount,
        amount, note, reference 
;

@defineDocTemplate(outgoingPayment, 'исходящего платежа');
@defineDocTemplateForm(outgoingPayment, p);
