MODULE OutgoingPaymentPrint;

REQUIRE OutgoingPayment, DocTemplate;

NAMESPACE Invoicing;

FORM printOutgoingPayment 'Исходящий платeж'

    OBJECTS o = OutgoingPayment PANEL 
    PROPERTIES(o)
        dateTime, number,
        namePartner, namePartnerAccount,
        nameCompany, nameCompanyAccount,
        amount, note, reference 
;

@defineDocTemplateType(outgoingPayment, 'исходящего платежа');
@defineDocTemplateTypeForm(outgoingPayment, p);
