MODULE MyCompany;

REQUIRE Eval, ProcessMonitor, Backup,
        MasterDataP,
        Inventory,
        Invoicing, InvoicingInventory,
        Purchase,
        Sales,
        Retail,  
        Manufacturing,
        ProjectManagement,
        BillReceiptCost, BillReceiptCostService; // initialize after Purchase

EXTEND CLASS Theme {
    sketchy 'Sketchy',
    yeti 'Yeti',
    lux 'Lux',
    flatly 'Flatly',
    darkly 'Darkly',
    minty 'Minty',
    quartz 'Quartz',
    lumen 'Lumen'
}