MODULE InvoicePartner;

REQUIRE InvoiceDebt;

NAMESPACE Invoicing;

EXTEND FORM partner
    OBJECTS i = Invoice
    PROPERTIES(i) READONLY nameStatus, number, dateTime, dueDateTime, note, untaxedAmount, totalTax, totalAmount, paid
    PROPERTIES(i) EDIT
    FILTERS customer(i) = p
;

DESIGN partner {
    tabs {
        NEW invoices {
            caption = 'Расходные накладные';
            MOVE BOX(i);
        }
    }
}
