MODULE InvoicePartner;

REQUIRE InvoiceDebt;

NAMESPACE Invoicing;

EXTEND FORM partner
    OBJECTS i = Invoice
    PROPERTIES(i) READONLY nameStatus, number, dateTime, dueDateTime, note, untaxedAmount, taxAmount, amount, paid
    PROPERTIES(i) NEWSESSION EDIT
    FILTERS customer(i) = p
;

DESIGN partner {
    tabs {
        NEW invoices {
            caption = 'Реализации';
            MOVE BOX(i);
        }
    }
}
