MODULE InvoiceSearch;

REQUIRE Invoicing, InvoiceDone, InventoryReport, Doc;

NAMESPACE Invoicing;

@defineDocSearch(invoice, item, quantity, i);

DESIGN invoice {
    box22 {
        type = TABBED;
        NEW pane33 {
            caption = 'Подбор';
            type = SPLITH;
            fill = 1;
            MOVE BOX(TREE categories);
            MOVE BOX(itm) { 
                fill = 2;
            }
        }   
    }
}
