MODULE InvoicePartner;

REQUIRE InvoiceDebt;

NAMESPACE Invoicing;

EXTEND FORM partner
    OBJECTS i = Invoice
    PROPERTIES(i) READONLY number, dateTime, deliveryDateTime, imagedNameStatus, nameType, dueDateTime, note, untaxedAmount, taxAmount, amount, paid
    PROPERTIES(i) NEWSESSION EDIT
    FILTERS customer(i) = p
;

DESIGN partner {
    tabs {
        MOVE BOX(i) { caption = 'Invoices'; }
    }
}
