MODULE InvoiceItem;

REQUIRE Invoice;

NAMESPACE Invoicing;

EXTEND FORM item
    OBJECTS il = InvoiceLine
    PROPERTIES(il) READONLY nameStatus, number, dateTime, nameCustomer, nameCompany, quantity, price
    PROPERTIES(il) NEWSESSION EDIT
    FILTERS item(il) = i
;

DESIGN item {
    operations {
        NEW invoices {
            caption = 'Реализации';
            MOVE BOX(il);
        }
    }
}