MODULE InvoiceUom;

REQUIRE Invoice, PartnerUom, ItemUom;

NAMESPACE Invoicing;

@defineDocPartnerUom(Invoice);
@defineDocPartnerQuantity(Invoice);
@defineDocPartnerPrice(Invoice);

EXTEND FORM invoice
    PROPERTIES(l) SHOWIF otherUom(customer(i)) BEFORE quantity(l) BACKGROUND RGB(255,212,255)
                  namePartnerUom, 
                  partnerQuantity ON CHANGE changePartnerQuantity(l),
                  partnerPrice ON CHANGE changePartnerPrice(l)
;
