MODULE IncomingPaymentAnalyticAccount;

REQUIRE AnalyticAccount, IncomingPayment, IncomingPaymentType;

NAMESPACE Invoicing;

@definePaymentTypeAnalytic(incoming);

analyticAccount 'Analytic account' = DATA AnalyticAccount (IncomingPayment);
nameAnalyticAccount 'Analytic account' (IncomingPayment p) = name(analyticAccount(p));

EXTEND FORM incomingPayments PROPERTIES READONLY nameAnalyticAccount(p);

@definePaymentAnalytic(incoming);