MODULE DiscountOnDashboard;

REQUIRE Invoice, DiscountCard, PosDashboard, DiscountCardInvoice;

NAMESPACE Retail;

EXTEND FORM posDashboard
    PROPERTIES(i) idDiscountCard
;

DESIGN posDashboard {
    invoice {
            MOVE PROPERTY(idDiscountCard(i)) AFTER PROPERTY(nameCustomer(i));
    }
}

processBarcode (Invoice i, STRING[20] b) + {
    FOR DiscountCard dc = discountCard(b) DO {
        discountCard(i) <- discountCard(b);
        consumedBarcode() <- TRUE;
    }
}