MODULE IncomingPaymentPrint;

REQUIRE IncomingPayment, DocTemplate;

NAMESPACE Invoicing;

FORM printIncomingPayment 'Входящий платeж'

    OBJECTS o = IncomingPayment PANEL 
    PROPERTIES(o)
        dateTime, number,
        namePartner, namePartnerAccount,
        nameCompany, nameCompanyAccount,
        amount, note, reference 
;

@defineDocTemplateType(incomingPayment, 'входящего платежа');
@defineDocTemplateTypeForm(incomingPayment, p);