MODULE MyCompanyPl;

REQUIRE MyCompany,
        LegalEntityPl, LegalEntityImportPl, TaxInitialPl,
        RegonDaneSzukajPodmity,
        PurchaseOrderPrintInitialPl,
        SalesOrderPrintInitialPl,
        InvoicePrintInitialPl,
        BillCorrection, BillCorrectionDebt, InvoiceCorrection, InvoiceCorrectionDebt,
        InvoiceAdvance,
        KSeF, KSeFToken, KSeFFakturaQuery, KSeFBill, KSeFInvoiceSend, KSeFScheduler;