MODULE PayslipInitial;

REQUIRE PayslipCategory, DefaultData;

NAMESPACE Payroll;

loadDefaultData () + {
    NEW c = PayslipCategory {
        name(c) <- 'Salary';
        editable(c) <- TRUE;
    }

    NEW c = PayslipCategory {
        name(c) <- 'Bonus';
        editable(c) <- TRUE;
    }

    NEW c = PayslipCategory {
        name(c) <- 'Tax';
        deduction(c) <- TRUE;
        editable(c) <- TRUE;
    }
}
