MODULE MyCompanyRu;

REQUIRE MyCompany,
        LegalEntityRu, LegalEntityImportRu, DaDataLegalEntityFind,
        InventoryRu,
        InvoicingRu, 
        PurchaseRu,
        SalesRu,
        CashRegisterAtol,
        SUZ,
        GISMTDocumentDone, GISMTManufacturingOrderIntroduceGoods, GISMTReceiptAcceptGoods, 
        GISMTShipmentShipGoods, GISMTShipmentShipReceipt, GISMTScrapReceipt,
        EnterpriseDataMyCompany;