MODULE Purchase;

REQUIRE PurchaseSettings, PurchaseOrder,
        SalesOrderPartner, SalesOrderItem,
        PurchaseOrderSent, PurchaseOrderConfirmed, PurchaseOrderCanceled, PurchaseOrderLocked,
        PurchaseOrderItem, PurchaseOrderPartner, PurchaseOrderPrint, 
        PurchasePricelist, PurchasePricelistItem, PurchasePricelistPartner,
        PurchaseOrderReceipt, PurchaseOrderBill,
        PurchaseReport;
