MODULE PurchaseOrderStatusDraft;

REQUIRE PurchaseOrder, PurchaseOrderStatus;

NAMESPACE Purchase;

EXTEND CLASS OrderStatus {
    draft 'Черновик запроса'
}

readonly (OrderLine l) += WHEN NOT status(order(l)) = OrderStatus.draft THEN TRUE;
readonly (Order o) += WHEN NOT status(o) = OrderStatus.draft THEN TRUE;

status(Order o) += WHEN o IS Order THEN OrderStatus.draft;
colorStatus(Order o) += WHEN status(o) == OrderStatus.draft THEN RGB(255,255,255);


