MODULE PurchaseSettings;

NAMESPACE Purchase;

FORM options 'Настройки'; 

DESIGN options {
    OBJECTS {
        NEW tabbedPane {
            type = TABBED;
            fill = 1;
        }
    }
} 

NAVIGATOR {
    NEW FOLDER purchase 'Закупки' WINDOW toolbar{
        NEW FOLDER operations 'Операции' {  
        }
        NEW FOLDER settings 'Настройка' {
            NEW options;        
        }
    }
}