MODULE ShipmentSearch;

REQUIRE Shipment, ResLedger, Doc;

NAMESPACE Inventory;

available 'Доступный остаток' (Shipment s, Product p) = available(location(s), p);

@defineDocSearch(shipment, product, initialDemand, s, canBeSold);

EXTEND FORM shipment
    PROPERTIES (s, itm) available
    FILTERGROUP  available
        FILTER 'Остатки' available(s, itm) 'F5' DEFAULT
    
    FILTERGROUP active
        FILTER 'Активный' active(itm) 'F10' DEFAULT  
;