MODULE ShipmentPartner;

REQUIRE ShipmentDone;

NAMESPACE Inventory;

EXTEND FORM partner
    OBJECTS s = Shipment
    PROPERTIES(s) READONLY nameStatus, scheduledDateTime, executionDateTime, number, nameType, nameLocation, note
    PROPERTIES(s) EDIT
    FILTERS customer(s) = p
;

DESIGN partner {
    tabs {
        NEW shipments {
            caption = 'Отгрузки';
            MOVE BOX(s);
        }
    }
}
