MODULE ProjectInitial;

REQUIRE Project;

NAMESPACE ProjectManagement;

loadDefaultData () + {
    NEW r = ProjectType {
        name(r) <- 'Project';
        id(r) <- r'project';
        NEW n = Numerator {
            name(n) <- 'Project';
            series(n) <- 'PRT';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(r) <- n;
        }
    }
}
