MODULE ManufacturingSettings;

NAMESPACE Manufacturing;

FORM options 'Настройки'
;

DESIGN options {
    OBJECTS {
        type = CONTAINERV;
    }
}

NAVIGATOR {
    NEW FOLDER manufacturing 'Производство' WINDOW toolbar {
        NEW FOLDER operations 'Операции' {  
        }
        NEW FOLDER reports 'Отчеты' {  
        }
        NEW FOLDER settings 'Настройка' {
            NEW options;
        }
    }  
}