MODULE Manufacturing;

REQUIRE ManufacturingSettings, ManufacturingOrder, BoM, 
    Operation, ManufacturingOrderStatus, ManufacturingOrderInProgress, ManufacturingOrderRes,
    ManufacturingOrderDone, ManufacturingOrderRes, ManufacturingOrderInv, ManufacturingOrderCanceled,
    ManufacturingOrderPrint, ManufacturingOrderReport, ManufacturingOrderCost, 
    UnbuildOrder, UnbuilOrderStatus, UnbuildOrderDone, UnbuildOrderInv, 
    UnbuildOrderInventoryMoves, ManufactoringOrderInventoryMoves;
