MODULE Manufacturing;

REQUIRE ManufacturingSettings, ManufacturingNavigator, ManufacturingOrder, ManufacturingReadiness, BoM, BoMType, 
    Operation, ManufacturingToItem, ManufacturingOrderStatus, ManufacturingOrderInProgress, ManufacturingOrderRes,
    ManufacturingOrderDone, ManufacturingOrderRes, ManufacturingOrderInv, ManufacturingOrderCanceled,
    ManufacturingOrderPrint, ManufacturingOrderReport, UnbuildOrder, UnbuilOrderStatus, UnbuildOrderDone, UnbuildOrderInv, 
    UnbuildOrderInventoryMoves, ManufactoringOrderInventoryMoves;
