MODULE ProductMoves;

REQUIRE InvLedger;

NAMESPACE Inventory;

FORM productMoves 'Движение товара'
    OBJECTS il = InvLedger
    PROPERTIES(il) READONLY class, dateTime, number, nameProduct, quantity, nameFromLocation, nameToLocation, namePartner
    PROPERTIES(il) NEWSESSION EDIT 
    FILTERGROUP active
        FILTER 'Активный' active(il) DEFAULT

    LIST InvLedger OBJECT il
;

NAVIGATOR {
    reporting {
        NEW productMoves;
    }
}