MODULE ProjectTimeEntryAssignment;

REQUIRE ProjectTimeEntry, ProjectAssignment;

NAMESPACE ProjectManagement;

EXTEND FORM timeEntries
    FILTERS hasAccess(project(t), currentUser()) OR accessAllProjects(currentUser()) OR employee(t) = currentUser()
;

WHEN LOCAL SET(TimeEntry e IS TimeEntry) AND defaultProject(employee(e)) AND NOT CHANGED(project(e)) DO
    project(e) <- defaultProject(employee(e));