MODULE OutgoingPaymentAnalyticAccount;

REQUIRE AnalyticAccount, OutgoingPayment, OutgoingPaymentType;

NAMESPACE Invoicing;

@definePaymentTypeAnalytic(outgoing);

analyticAccount 'Analytic account' = DATA AnalyticAccount (OutgoingPayment);
nameAnalyticAccount 'Analytic account' (OutgoingPayment p) = name(analyticAccount(p));

EXTEND FORM outgoingPayments PROPERTIES READONLY nameAnalyticAccount(p);

@definePaymentAnalytic(outgoing);
