MODULE ScrapInv;

REQUIRE ScrapCanceled, InvLedger;

NAMESPACE Inventory;

EXTEND CLASS ScrapLine : InvLedger;
active(ScrapLine l) += active(scrap(l));

type(ScrapLine l) += nameType(scrap(l));

dateTime(ScrapLine l) += dateTime(scrap(l));
number(ScrapLine l) += number(scrap(l));

fromLocation(ScrapLine l) += location(scrap(l));

product(ScrapLine l) += product(l);
quantity(ScrapLine l) += quantity(l);

edit (ScrapLine l) + { edit(scrap(l)); } 