MODULE ScrapInv;

REQUIRE ScrapCanceled, InvLedger;

NAMESPACE Inventory;

EXTEND CLASS ScrapLine : InvLedger;
active(ScrapLine l) += active(scrap(l));

dateTime(ScrapLine l) += date(scrap(l));
number(ScrapLine l) += number(scrap(l));

fromLocation(ScrapLine l) += locationFrom(scrap(l));

product(ScrapLine l) += product(l);
quantity(ScrapLine l) += quantity(l);

description(ScrapLine l) += 'Списание' IF l IS ScrapLine;

edit (ScrapLine l) + { edit(scrap(l)); } 