MODULE ScrapCost;

REQUIRE CostLedger, Scrap, CostLocation;

NAMESPACE Inventory;

CLASS ScrapCostLedger : OutCostLedger;
scrapLedger = AGGR ScrapCostLedger WHERE quantity(ScrapLine line) AND done(scrap(line));

dateTime(ScrapCostLedger l) += date(scrap(line(l)));
location(ScrapCostLedger l) += costLocation(locationFrom(scrap(line(l))));

product(ScrapCostLedger l) += product(line(l));
quantity(ScrapCostLedger l) += quantity(line(l));

edit(ScrapCostLedger l) + { edit(line(l)); }