MODULE SalesPriceTypeInitial;

REQUIRE SalesPriceType;

NAMESPACE Sales;

loadDefaultData() + {
    NEW t = PriceType {
        name(t) <- 'Оптовая';
        id(t) <- 'wholesale';
    }    

    NEW t = PriceType {
        name(t) <- 'Розничная';
        id(t) <- 'retail';
        taxIncluded(t) <- TRUE;
    }    

    NEW t = PriceType {
        name(t) <- 'Акционная';
        id(t) <- 'promotion';
        taxIncluded(t) <- TRUE;
    }    
}