MODULE SalesPriceTypeInitial;

REQUIRE SalesPriceType;

NAMESPACE Sales;

loadDefaultData() + {
    NEW t = PriceType {
        name(t) <- 'Wholesale';
        id(t) <- 'wholesale';
    }    

    NEW t = PriceType {
        name(t) <- 'Retail';
        id(t) <- 'retail';
        taxIncluded(t) <- TRUE;
    }    

    NEW t = PriceType {
        name(t) <- 'Promotional';
        id(t) <- 'promotion';
        taxIncluded(t) <- TRUE;
    }    
}