MODULE BillCustomsDeclarationInitial;

REQUIRE BillCustomsDeclaration;

NAMESPACE Invoicing;

loadDefaultData () + {
    NEW t = BillType {
        name(t) <- 'Import';
        id(t) <- 'import';
        import(t) <- TRUE;
        NEW n = Numerator {
            name(n) <- 'Import';
            series(n) <- 'IMP';
            minValue(n) <- 1;
            maxValue(n) <- 999999;
            stringLength(n) <- 6;
            numerator(t) <- n;
        }
    }
}