MODULE InvoicingSettings;

NAMESPACE Invoicing;

FORM options 'Settings'
;

DESIGN options {
    OBJECTS {
        NEW tabbedPane {
            type = TABBED;
            fill = 1;
        }
    }
}

NAVIGATOR {
    NEW FOLDER invoicing 'Invoicing' WINDOW toolbar IMAGE 'invoicing.png' {
        NEW FOLDER operations 'Operations' {
        }
        NEW FOLDER reporting 'Reporting' { 
        }
        NEW FOLDER settings 'Configuration' {
            NEW options;        
        }
    }
}
