MODULE InvoicingSettings;

NAMESPACE Invoicing;

FORM options 'Настройки'
;

DESIGN options {
    OBJECTS {
        NEW tabbedPane {
            type = TABBED;
            fill = 1;
        }
    }
}

NAVIGATOR {
    NEW FOLDER invoicing 'Расчеты' WINDOW toolbar IMAGE 'invoicing.png' {
        NEW FOLDER operations 'Операции' {
        }
        NEW FOLDER reporting 'Отчеты' { 
        }
        NEW FOLDER settings 'Настройка' {
            NEW options;        
        }
    }
}
