MODULE SalesOrderPartner;

REQUIRE SalesOrderStatus;

NAMESPACE Sales;

EXTEND FORM partner
    OBJECTS sl = Order
    PROPERTIES(sl) READONLY nameStatus, dateTime, seriesNumber, scheduledDate, nameCustomer, nameRepresentative
    PROPERTIES(sl) READONLY untaxedAmount, totalTax, totalAmount
    FILTERS customer(sl) = p
;

DESIGN partner {
    tabs {
        NEW sOrders {
            caption = 'Заказы на продажу';
            MOVE BOX(sl);
        }
    }
}
