MODULE SalesOrderSearch;

REQUIRE SalesOrder, ResLedger;

NAMESPACE Sales;

@defineDocSearch(order, item, quantity, 'Кол-во', o, canBeSold);

// available
available 'Доступно' (Order o, Product p) = prevAvailableRec(location(o), p); 

EXTEND FORM order
    PROPERTIES(o, itm) READONLY available
    FILTERGROUP available
        FILTER 'Доступно' available(o, itm) OR NOT itm IS Product 'F5' DEFAULT
;

@defineBarCodeSearch(order, o, l, item, quantity);
