MODULE SalesOrderItem;

REQUIRE SalesOrder;

NAMESPACE Sales;

EXTEND FORM item
    OBJECTS sl = OrderLine
    PROPERTIES(sl) READONLY nameStatus, dateTime, number, nameCustomer, nameLocation
    PROPERTIES(sl) READONLY nameItem, quantity, unitPrice
    FILTERS item(sl) = i
;

DESIGN item {
    tabs {
        NEW sOrders {
            caption = 'Заказы на продажу';
            MOVE BOX(sl);
        }
    }
}