MODULE PosDashboardShipment;

REQUIRE PosDashboardSearch, SessionShipment, InvoiceShipmentSearch;

NAMESPACE Retail;

EXTEND FORM posDashboard
    PROPERTIES(i) nameLocation

    PROPERTIES(i, it) READONLY available
    EXTEND FILTERGROUP searchFilter
        FILTER 'Доступно' available(i, it) OR NOT it IS Product 'F10'
;

DESIGN posDashboard {
    invoice {
        MOVE PROPERTY(nameLocation(i));
    }
}