MODULE PurchasePricelistPartner;

REQUIRE PurchasePricelist;

NAMESPACE Purchase;

EXTEND FORM partner
    OBJECTS prp = Pricelist 
    PROPERTIES(prp) READONLY number, startDateTime, endDateTime, imagedNameStatus BACKGROUND colorStatus(prp), note
    PROPERTIES(prp) NEWSESSION EDIT 
    FILTERS vendor(prp) = p
;

DESIGN partner {
    vendor {
        MOVE BOX(prp) { fill = 1; caption = ''; };
    }
}
