MODULE CostLocation;

REQUIRE Location;

NAMESPACE Inventory;

calcCost 'Cost calculation' = DATA BOOLEAN (Location);
EXTEND FORM location
    PROPERTIES(l) calcCost
;
DESIGN location {
    params {
        MOVE PROPERTY(calcCost(l));
    }
}

EXTEND FORM locations
    PROPERTIES(l) READONLY calcCost
;

costLocation (Location l) = 
    GROUP LAST Location parent ORDER DESC level(l, parent) 
          WHERE calcCost(parent) OR NOT parent(parent) MATERIALIZED;
