MODULE Sales;

REQUIRE SalesSettings, SalesOrder,  
        SalesOrderStatus, SalesOrderOfferSent, SalesPrintOffer, SalesSendOffer,
        SalesOrderPartner, SalesOrderItem, SalesPriceTypeMarkup, SalesPriceListStatus, SalesPriceListDone,
        SalesOrderConfirmed, SalesSendOrder, SalesPrintOrder, SalesOrderCanceled, SalesOrderLocked, 
        SalesOrderShipment, SalesOrderInvoice, SalesOrderSearch, SalesOrderHistory,   
        SalesPricelist, SalesPricelistSearch, SalesPricelistItem, SalesPricelistChange;