MODULE Sales;

REQUIRE SalesSettings, 
        SalesOrder, SalesOrderOfferSent, SalesOrderConfirmed, SalesOrderCanceled, SalesOrderLocked, 
        SalesOrderPrint, SalesOrderPartner, SalesOrderItem,
        SalesPricelist, SalesPriceListDone, SalesPriceTypeMarkup, 
        SalesPricelistSearch, SalesPricelistItem, SalesPricelistChange, SalesPricelistPrint,
        SalesOrderShipment, SalesOrderInvoice,   
        SalesReport;